chore: remove shiny refs

diff --git a/start-k8s b/start-k8s
--- a/start-k8s
+++ b/start-k8s
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 set -eu
-# example use case: ./start-k8s-shiny production
+# example use case: ./start-k8s production
 # Set the environment variable to the first command-line argument or default to 'staging'
 ENV=${1:-staging}
 if [[ "$ENV" != "staging" && "$ENV" != "production" ]]; then
@@ -20,14 +20,14 @@ chmod +x k8s/
 kubectl create namespace beebop --dry-run=client -o yaml | kubectl apply -f -
 
 # Run the script to configure SSL (assuming it's in the k8s directory)
-k8s/configure_ssl  ||  { echo "Error: Failed to configure SSL"; exit 1; }
+k8s/configure_ssl $ENV  ||  { echo "Error: Failed to configure SSL"; exit 1; }
 
 # Run the script to configure secrets (assuming it's in the k8s directory)
-k8s/configure_secrets  ||  { echo "Error: Failed to configure secrets"; exit 1; }
+k8s/configure_secrets $ENV ||  { echo "Error: Failed to configure secrets"; exit 1; }
 
 # Apply Kubernetes manifests from overlays based on the specified or default environment
 kubectl apply -k "k8s/overlays/$ENV"
 
-# Wait for the 'shiny-deploy' deployment to be in the 'available' condition within the 'twinkle' namespace
+# Wait for the 'beebop-deploy-py-api' deployment to be in the 'available' condition within the 'beebop' namespace
 echo 'Waiting for pods to be ready...'
 kubectl wait -n beebop --for=condition=available --timeout=300s deployment/beebop-deploy-py-api
